# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: PZXBC's blog
subtitle: 学以致用
description: 希望能够每天提升一点~~~
author: 盆栽小白菜
email: pzxbc@qq.com
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.pzxbc.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
skip_render:
  - googleb0b30ea37bb4c914.html
  - .nojekyll

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
highlight:
  enable: true
  line_number: false
  tab_replace:

# Category & Tag
default_category: 未分类
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: localhost
logger: false
logger_format: dev

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname:

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
baidusitemap:
path: baidusitemap.xml
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: next
exclude_generator:

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
- type: git
  repository: git@github.com:pzxbc/pzxbc.github.io.git
  branch: master

# json-content
jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true

# plugins

# hexo-directory-category
auto_dir_categorize:
	enable: true  # options:true, false; default is true
  force: false # options:true, false; default is false

# hexo-symbols-count-time
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true

# theme
theme_config:
  favicon:
    small: /images/favicon-16x16-next.png
    medium: /images/favicon-32x32-next.png
    apple_touch_icon: /images/apple-touch-icon-next.png
    safari_pinned_tab: /images/logo.svg

  keywords: "pzxbc, 记录"

  menu:
    home: / || home
    about: /about/ || user
    tags: /tags/ || tags
    categories: /categories/ || th
    archives: /archives/ || archive
    #schedule: /schedule/ || calendar
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat

  # Enable/Disable menu icons / item badges.
  menu_settings:
    icons: true
    # 显示数量
    badges: true

  scheme: Gemini
  social:
    GitHub: https://github.com/pzxbc || github
    E-Mail: mailto:pzxbc@qq.com || envelope

  # Creative Commons 4.0 International License. # http://creativecommons.org/
  # Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
  creative_commons: by-nc-nd

  symbols_count_time:
    separated_meta: true
    item_text_post: true
    item_text_total: false
    awl: 2
    wpm: 300

  # Wechat Subscriber
  #wechat_subscriber:
    #enabled: true
    #qcode: /path/to/your/wechatqcode ex. /uploads/wechat-qcode.jpg
    #description: ex. subscribe to my blog by scanning my public wechat account

  # Reward
  #reward_comment: Donate comment here
  #wechatpay: /images/wechatpay.jpg
  #alipay: /images/alipay.jpg
  #bitcoin: /images/bitcoin.png

  # Related popular posts
  # Dependencies: https://github.com/tea3/hexo-related-popular-posts
  related_posts:
    enable: true
    title: # custom header, leave empty to use the default one
    display_in_home: false
    params:
      maxCount: 5
      #PPMixingRate: 0.0
      #isDate: false
      #isImage: false
      #isExcerpt: false

  # Declare license on posts
  post_copyright:
    enable: false
    license: <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" rel="external nofollow" target="_blank">CC BY-NC-ND 4.0</a>

  # Disqus
  # 国内屏蔽了...
  disqus:
    enable: false
    shortname: 'blog-pzxbc-com'
    count: true
    lazyload: false

  valine:
    enable: true # When enable is set to be true, leancloud_visitors is recommended to be closed for the re-initialization problem within different leancloud adk version.
    appid: 'EzRRCR6TWWbI6tznEWKbd5MH-gzGzoHsz' # your leancloud application appid
    appkey: 'rWMYX8Xg9HiykSb6BrfvF0fD' # your leancloud application appkey
    notify: false # mail notifier , https://github.com/xCss/Valine/wiki
    verify: false # Verification code
    placeholder: Just go go # comment box placeholder
    avatar: wavatar # gravatar style
    guest_info: nick,mail,link # custom comment header
    pageSize: 10 # pagination size
    visitor: true # leancloud-counter-security is not supported for now. When visitor is set to be true, appid and appkey are recommended to be the same as leancloud_visitors' for counter compatibility. Article reading statistic https://valine.js.org/visitor.html

  needmoreshare2:
    enable: true
    postbottom:
      enable: true
      options:
        iconStyle: box
        boxForm: horizontal
        position: bottomCenter
        networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook
    float:
      enable: true
      options:
        iconStyle: box
        boxForm: horizontal
        position: middleRight
        networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook

  google_site_verification: 'AEwKHvOWNqrIhtqouotdW_pHO0lGcAIUc_Dzfo4T894'
  google_analytics: 'UA-19482318-2'
  bing_site_verification: '6F83C300A4B93AB7A45420F532B43FFE'
  baidu_push: true

  # Reading progress bar
  # Dependencies: https://github.com/theme-next/theme-next-reading-progress
  reading_progress:
    enable: true
    color: "#37c6c0"
    height: 2px

  fancybox: true